---
title: "About"
author: "Jefferson Ong"
date: "5/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My interest in statistics and math, Its a subject that I often do well in and understand easier than others. I believe a great deal of that comes from trying to understand the foundational understanding of the formulas and functions we're given. Things aren't just variables we plug into a function and get an output. Something more exciting is happening behind the close doors. 

A great example of this is the fundamental theorem of calculus: $$\frac{d}{dx}\int_a^b \! f(t) \, \mathrm{d}t = f(x)$$

I won't be going through the [proof](https://en.wikipedia.org/wiki/Fundamental_theorem_of_calculus) here, but its essentially the relationship between derivatives and integrals. Where one takes the slope of a line tangent to the function at a point and the other takes the area of the function in a set interval. It's difficult to see this connection for what it is. One could think of derivatives as velocity or some rate of change while the integral similar to taking an area of a square but it's more of a dance with how we've define them mathematically and the theorem arises from the definitions. 

This idea applies to the statistical techniques we use, from the basic bayesian probabilties to classical regression. It's getting to the heart of what is true.
I've been learning more about machine learning and AI, the process of training and testing, tuning parameters, etc. The predictive capabilities is what's important but the field has a lot of exciting implications. There's the idea of a strong AI and what it means for us as a species. There's the parallels of a neural network to our own neurons, what it means for us to think. Are we following similar processes in our own consciousness? can we train ourselves in similar processes? Are there going to be robots soon? etc. The increase in computing power has allowed us to asking these larger than life and look forward to the future with awe or dread, but exciting nonetheless.


*"Success in creating AI would be the biggest event in human history. Unfortunately, it might also be the last, unless we learn how to avoid the risks."* -- Stephen Hawking










