---
title: "Jefferson Ong's Resume"
---

* * *




### EDUCATIONAL BACKGROUND

08/18—05/20: **Bachelor of Mathematics**, _Appalachian State University_ – Boone, NC Cumulative `GPA: 3.0/4.0` Math concentration in Statistics

08/16—05/18: **Associates in Science**, _Fayetteville Technical College_ – Fayetteville, NC Cumulative `GPA: 3.8/4.0` concentration in mathematics and chemistry. 

***

### WORK EXPERIENCE

09/18—05/20: **Undergraduate Research**, _S-STEM Scholarship_ – Boone, NC Worked in a group of five on western tonal system to a generalized microtonal system using modular arithmetic.


01/18—08/18: **Event Specialist**, _Advantage Solutions_ – Fayetteville, NC Cooking, preparing, and serving food and drink samples to Sam’s Club members. Informing and selling the product, as well as keeping detailed records and stocks




01/18—06/18: **Hospice Volunteer**, _Cape Fear Valley Health_ – Fayetteville, NC Provide supportive care to patient in the final stage of terminal illness. Focusing on quality of life through active listening and emotional support.


* * *


03/17—05/18: **Honor Society**, *Phi Theta Kappa*– Fayetteville, NC International honor society of two-year colleges and academic programs. 


02/12—06/15: **Chess Club President**, *Pine Forest Chess Club* – Fayetteville, NC Advertising and event management of chess club events. Teaching new members rules and strategy of chess. 

## Page length testing

R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

## latex testing

$$\sin(x) = \frac{3}{4}$$




